python3 /home/mikey/Documents/code/convertMacros/convertMacros.py -i "/home/mikey/Documents/code/FFBE-Macros/Kawoxux/Exploration Automation - Nox/MagicLibrary/Magic Library.txt" -o "/home/mikey/Documents/code/FFBE-Macros/Kawoxux/Exploration Automation - Nox/MagicLibrary/Magic Library-MEmu.txt" --outtype memu
python3 /home/mikey/Documents/code/convertMacros/convertMacros.py -i "/home/mikey/Documents/code/FFBE-Macros/Kawoxux/Exploration Automation - Nox/MagicLibrary/Magic Library-a0.8.txt" -o "/home/mikey/Documents/code/FFBE-Macros/Kawoxux/Exploration Automation - Nox/MagicLibrary/Magic Library-a0.8-MEmu.txt" --outtype memu

python3 /home/mikey/Documents/code/convertMacros/convertMacros.py -i "/home/mikey/Documents/code/FFBE-Macros/Kawoxux/Exploration Automation - Nox/MagicLibrary/Magic Library.txt" -o "/home/mikey/Documents/code/FFBE-Macros/Kawoxux/Exploration Automation - Nox/MagicLibrary/Magic Library-oldnox.txt" --outtype nox
python3 /home/mikey/Documents/code/convertMacros/convertMacros.py -i "/home/mikey/Documents/code/FFBE-Macros/Kawoxux/Exploration Automation - Nox/MagicLibrary/Magic Library-a0.8.txt" -o "/home/mikey/Documents/code/FFBE-Macros/Kawoxux/Exploration Automation - Nox/MagicLibrary/Magic Library-a0.8-oldnox.txt" --outtype nox

python3 /home/mikey/Documents/code/convertMacros/convertMacros.py -i "/home/mikey/Documents/code/FFBE-Macros/Kawoxux/Exploration Automation - Nox/MagicLibrary/ML Full v0.11" -o "/home/mikey/Documents/code/FFBE-Macros/Kawoxux/Exploration Automation - Nox/MagicLibrary/ML Full v0.11-memu.txt" --outtype memu
python3 /home/mikey/Documents/code/convertMacros/convertMacros.py -i "/home/mikey/Documents/code/FFBE-Macros/Kawoxux/Exploration Automation - Nox/MagicLibrary/ML Full v0.11" -o "/home/mikey/Documents/code/FFBE-Macros/Kawoxux/Exploration Automation - Nox/MagicLibrary/ML Full v0.11-oldnox" --outtype nox

python3 /home/mikey/Documents/code/convertMacros/convertMacros.py -i "/home/mikey/Documents/code/FFBE-Macros/Kawoxux/Exploration Automation - Nox/MagicLibrary/5a6d178973e94fa1a35f9fa874c73e62" -o "/home/mikey/Documents/code/FFBE-Macros/Kawoxux/Exploration Automation - Nox/MagicLibrary/5a6d178973e94fa1a35f9fa874c73e62-MEmu.txt" --outtype memu 
